/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int SLPAR = 11;
  /** RegularExpression Id. */
  int SRPAR = 12;
  /** RegularExpression Id. */
  int EL = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int LET = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int ASSIGN = 19;
  /** RegularExpression Id. */
  int DEREF = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int END = 26;
  /** RegularExpression Id. */
  int SEQ = 27;
  /** RegularExpression Id. */
  int PRINT = 28;
  /** RegularExpression Id. */
  int FUN = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int ARROW = 31;
  /** RegularExpression Id. */
  int COLON = 32;
  /** RegularExpression Id. */
  int ARRAY = 33;
  /** RegularExpression Id. */
  int GARRAY = 34;
  /** RegularExpression Id. */
  int SARRAY = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int BOOL = 37;
  /** RegularExpression Id. */
  int UNIT = 38;
  /** RegularExpression Id. */
  int REF = 39;
  /** RegularExpression Id. */
  int Id = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int OR = 42;
  /** RegularExpression Id. */
  int NOT = 43;
  /** RegularExpression Id. */
  int LESS = 44;
  /** RegularExpression Id. */
  int GREATER = 45;
  /** RegularExpression Id. */
  int LESSEQ = 46;
  /** RegularExpression Id. */
  int GREATEREQ = 47;
  /** RegularExpression Id. */
  int EQ = 48;
  /** RegularExpression Id. */
  int EQUALS = 49;
  /** RegularExpression Id. */
  int NOTEQUALS = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"\\n\"",
    "\"false\"",
    "\"true\"",
    "\"let\"",
    "\"in\"",
    "\"new\"",
    "\":=\"",
    "\"!\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\";\"",
    "<PRINT>",
    "\"fun\"",
    "\",\"",
    "\"->\"",
    "\":\"",
    "\"array\"",
    "\"garray\"",
    "\"sarray\"",
    "\"int\"",
    "\"bool\"",
    "\"unit\"",
    "\"ref\"",
    "<Id>",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
  };

}
